name: CI - build & smoke

on:
  push:
    branches: [ develop/** ]
  pull_request:
    branches: [ main , develop ]
  workflow_dispatch: {}

jobs:
  build-and-capture:
    name: macOS build & capture
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install ffmpeg imagemagick xxd mednafen cc65 zsh

      - name: Ensure artifacts dir
        working-directory: ${{ github.workspace }}
        run: mkdir -p nes-ide/{artifacts,tmp}

      - name: Build example (cl65)
        working-directory: ${{ github.workspace }}/nes-ide/examples/hello-world
        run: |
          make clean
          make -j1

      - name: Run Mednafen (record) and capture
        working-directory: nes-ide/examples/hello-world
        env:
          MEDNAFEN_HOME: ${{ github.workspace }}/nes-ide/tmp/nes-ide_mednafen_home_ci
        run: |
          set -eux
          mkdir -p "$MEDNAFEN_HOME"
          if command -v mednafen >/dev/null 2>&1; then
            # On macOS runners, mednafen uses native windowing; record to file using -qtrecord
            mednafen -qtrecord "$MEDNAFEN_HOME/mednafen_record.mov" hello.nes &> "$MEDNAFEN_HOME/mednafen.log" &
            MFPID=$!
            sleep 2
            kill $MFPID || true
            wait $MFPID || true
          else
            echo "mednafen not available on runner"
          fi

      - name: Extract frame with ffmpeg if movie present
        env:
          MOVIE: ${{ github.workspace }}/nes-ide/tmp/nes-ide_mednafen_home_ci/mednafen_record.mov
          SNAPSHOT: ${{ github.workspace }}/nes-ide/artifacts/hello_mednafen_snapshot.png
        working-directory: nes-ide/artifacts
        run: |
          if [[ -n "$MOVIE" && -f "$MOVIE" ]]; then
            ffmpeg -y -i "$MOVIE" -frames:v 1 -q:v 2 "$SNAPSHOT" || true
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nes-ide-artifacts
          path: nes-ide/artifacts/
