name: CI - build & smoke

on:
  push:
    branches: [ develop/** ]
  pull_request:
    branches: [ main , develop ]
  workflow_dispatch: {}

jobs:
  build-and-capture:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        shell: zsh
        run: |
          # Use Homebrew on macOS; install if missing
          if ! command -v brew >/dev/null 2>&1; then
            echo "Homebrew not found; please pre-install on runner or set up Brew action." >&2
          fi
          if command -v brew >/dev/null 2>&1; then
            brew update || true
            brew install ffmpeg imagemagick xxd || true
            # mednafen and cc65 available via brew
            brew install mednafen cc65 || true
          fi

      - name: Ensure artifacts dir
        run: mkdir -p nes-ide/artifacts nes-ide/tmp

      - name: Build example (cl65)
        working-directory: nes-ide/examples/hello-world
        run: |
          make clean
          make -j1

      - name: Run Mednafen (record) and capture
        shell: zsh
        run: |
          set -eux
          cd nes-ide/examples/hello-world
          export MEDNAFEN_HOME=$(pwd)/../../tmp/nes-ide_mednafen_home_ci
          mkdir -p "$MEDNAFEN_HOME"
          if command -v mednafen >/dev/null 2>&1; then
            # On macOS runners, mednafen uses native windowing; record to file using -qtrecord
            mednafen -qtrecord "$MEDNAFEN_HOME/mednafen_record.mov" hello.nes &> "$MEDNAFEN_HOME/mednafen.log" &
            MFPID=$!
            sleep 2
            kill $MFPID || true
            wait $MFPID || true
          else
            echo "mednafen not available on runner"
          fi

      - name: Extract frame with ffmpeg if movie present
        shell: zsh
        run: |
          MOVIE=$(ls -1 ../../tmp/nes-ide_mednafen_home_ci/mednafen_record.mov 2>/dev/null || true)
          if [[ -n "$MOVIE" && -f "$MOVIE" ]]; then
            ffmpeg -y -i "$MOVIE" -frames:v 1 -q:v 2 ../../artifacts/hello_mednafen_snapshot.png || true
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nes-ide-artifacts
          path: nes-ide/artifacts/
