name: Roll & Smoke Test (macOS)

on:
  push:
    branches: [ develop/** ]
  pull_request:
    branches: [ main , develop ]
  workflow_dispatch: {}

jobs:
  build-and-capture:
    name: macOS build & capture
    runs-on: macos-latest
    env:
      LOGS: ${{ github.workspace }}/logs
      ARTIFACTS: ${{ github.workspace }}/artifacts
      HELLO_WORLD_ROM: ${{ github.workspace }}/nes-ide/examples/hello-world/hello.nes
      TMP: ${{ github.workspace }}/tmp
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1
        with:
          ffmpeg-version: release
          architecture: x64
          linking-type: static
          github-token: ${{ secrets.GITHUB_TOKEN }}   
          
      - name: Setup ImageMagick
        uses: mfinelli/setup-imagemagick@v7.0.1

      - name: Install remaining dependencies with brew
        run: |
          brew install mednafen cc65 zsh

      - name: Ensure artifacts dir
        working-directory: ${{ github.workspace }}
        run: mkdir -p {artifacts,logs,tmp}

      - name: Build example (cl65)
        working-directory: ${{ github.workspace }}/nes-ide/examples/hello-world
        run: make -j1

      - name: Run Mednafen (record) and capture
        working-directory: ${{ github.workspace }}/nes-ide/examples/hello-world
        run: |
          set -eux
          mednafen -qtrecord "$ARTIFACTS/mednafen_record.mov" "$HELLO_WORLD_ROM" &> "$LOGS/mednafen.log" &
            MFPID=$!
            sleep 2
            kill $MFPID || true
            wait $MFPID || true

      - name: Extract frame with ffmpeg if movie present
        env:
          MOVIE: $ARTIFACTS/mednafen_record.mov
          SNAPSHOT: $ARTIFACTS/mednafen_snapshot.png
        working-directory: ${{ github.workspace }}/artifacts/
        run: |
          if [[ -n "$MOVIE" && -f "$MOVIE" ]]; then
            ffmpeg -y -i "$MOVIE" -frames:v 1 -q:v 2 "$SNAPSHOT" || true
          fi
      
      - name: Package artifacts
        working-directory: $ARTIFACTS
        run: |
          set -eux
          find . -type f ! -name "*.tar.gz" | tar -czf artifacts.tar.gz -T - || true
          if [[ ! -s artifacts.tar.gz ]]; then
            echo "No artifact files found"
          fi || true

      - name: Package logs
        working-directory: $LOGS
        run: |
          set -eux
          find . -type f ! -name "*.tar.gz" | tar -czf logs.tar.gz -T - || true
          if [[ ! -s logs.tar.gz ]]; then
            echo "No log files found"
          fi || true

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: $LOGS/logs.tar.gz
          if-no-files-found: error

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: $ARTIFACTS/artifacts.tar.gz
          if-no-files-found: error
          retention-days: 5
